services:
  api:
    build:
      context: .
      dockerfile: HotelBookingPlatform.API/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__defaultDB=Server=db;Database=HotelBookingDB;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - InnfinitySecretKey=${InnfinitySecretKey}
      - InnfinityIssuer=App
      - InnfinityAudience=User
    networks:
      - innfinity_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - innfinity_network
    volumes:
      - mssql-data:/var/opt/mssql

networks:
  innfinity_network:

volumes:
  mssql-data:
