name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore 

    - name: Install dotnet-ef tool
      run: dotnet tool install --global dotnet-ef
      
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run migrations
      run: dotnet ef database update --verbose --context AppDbContext --connection "${{ secrets.DEFAULT_CONNECTION }}" --startup-project ./HotelBookingPlatform.API/HotelBookingPlatform.API.csproj
      env:
        DefaultConnection: ${{ secrets.DEFAULT_CONNECTION }}

    - name: Test API
      run: dotnet test HotelBookingPlatform.API.Tests --no-restore --verbosity normal

    - name: Test Domain
      run: dotnet test HotelBookingPlatform.Domain.Tests --no-restore --verbosity normal

    - name: Test Infrastructure
      run: dotnet test HotelBookingPlatform.Infrastructure.Tests --no-restore --verbosity normal

    - name: Test Infrastructure Integration
      run: dotnet test HotelBookingPlatform.Infrastructure.IntegrationTests --no-restore --verbosity normal

    - name: Test
      run: dotnet test --verbosity detailed
      env:
        DefaultConnection: ${{ secrets.DEFAULT_CONNECTION }}
