name: Create and Push Docker Image to Docker Hub

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    
    - name: Build the Docker image
      run: docker build -f ./HotelBookingPlatform.API/Dockerfile -t janaherself/hotel-booking-system:latest .

    - name: Push to Docker Hub
      run: docker push janaherself/hotel-booking-system:latest
    
